Repository ReachFive/identity-web-ui-sdk, pull requests merged in 2020-10, with the labels that each got.

#61 Implement Fido2 signup on the authentication widget
  package-lock.json
  package.json
  src/components/form/formControlsComponent.jsx
  src/components/form/formFieldFactory.js
  src/components/form/passwordSignupFormComponent.jsx
  src/components/form/webAuthAndPasswordButtonsComponent.jsx
  src/components/form/webAuthButtonsComponent.jsx
  src/widgets/auth/authWidget.js
  src/widgets/auth/views/loginWithWebAuthnViewComponent.jsx
  src/widgets/auth/views/signupViewComponent.jsx
  src/widgets/auth/views/signupWithPasswordViewComponent.jsx
  src/widgets/auth/views/signupWithWebAuthnViewComponent.jsx
  tests/widgets/auth/__snapshots__/authWidget.test.js.snap
  tests/widgets/auth/authWidget.test.js
  tests/widgets/passwordReset/__snapshots__/passwordResetWidget.test.js.snap
  tests/widgets/passwordless/__snapshots__/passwordlessWidget.test.js.snap
  tests/widgets/socialAccounts/__snapshots__/socialAccountsWidget.test.js.snap
Labels: enhancement, require review

#62 Release v1.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#63 Revert "Implement Fido2 signup on the authentication widget (#61)"
  package-lock.json
  package.json
  src/components/form/formControlsComponent.jsx
  src/components/form/formFieldFactory.js
  src/components/form/passwordSignupFormComponent.jsx
  src/components/form/webAuthAndPasswordButtonsComponent.jsx
  src/components/form/webAuthButtonsComponent.jsx
  src/widgets/auth/authWidget.js
  src/widgets/auth/views/loginWithWebAuthnViewComponent.jsx
  src/widgets/auth/views/signupViewComponent.jsx
  src/widgets/auth/views/signupWithPasswordViewComponent.jsx
  src/widgets/auth/views/signupWithWebAuthnViewComponent.jsx
  tests/widgets/auth/__snapshots__/authWidget.test.js.snap
  tests/widgets/auth/authWidget.test.js
  tests/widgets/passwordReset/__snapshots__/passwordResetWidget.test.js.snap
  tests/widgets/passwordless/__snapshots__/passwordlessWidget.test.js.snap
  tests/widgets/socialAccounts/__snapshots__/socialAccountsWidget.test.js.snap
Labels: bug

#64 Release v1.10.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#66 Basic form validation changes
  src/components/form/fieldCreator.jsx
  src/components/form/fields/passwordField.jsx
  src/components/form/formComponent.jsx
  src/widgets/auth/views/signupViewComponent.jsx
Labels: enhancement

#68 Use zxcvbn in form validation
  src/components/form/fields/passwordField.jsx
  src/widgets/auth/views/signupViewComponent.jsx
Labels: enhancement, require review

#67 Add a check rule for password strength
  src/components/form/fields/passwordField.jsx
  src/components/form/fields/passwordPolicyRules.jsx
Labels: enhancement

#69 Release v1.11.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#70 Release v1.11.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/fields/passwordField.jsx
  src/components/form/passwordPolicyComponent.jsx
Labels: bug, release
