Repository ReachFive/identity-web-ui-sdk, pull requests merged in 2020-09, with the labels that each got.

#56 Ajout d'un paramètre purpose lors du reset password.
  src/widgets/passwordReset/passwordResetWidget.jsx
Labels: enhancement, require testing

#59 Use the env variables in the CircleCi "reachfive" context
  .circleci/config.yml
Labels: bug

#60 Release v1.9.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
