Repository ReachFive/identity-web-ui-sdk, pull requests merged in 2020-11, with the labels that each got.

#72 Release v1.11.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/fields/passwordField.jsx
  src/components/form/fields/passwordPolicyRules.jsx
Labels: enhancement, release

#71 Fix the "showAuth" widget with the Fido2 signup feature
  package-lock.json
  package.json
  src/components/form/formControlsComponent.jsx
  src/components/form/formFieldFactory.js
  src/components/form/passwordSignupFormComponent.jsx
  src/components/form/webAuthAndPasswordButtonsComponent.jsx
  src/components/form/webAuthButtonsComponent.jsx
  src/icons/fingerprint.svg
  src/icons/keyboard.svg
  src/widgets/auth/authWidget.js
  src/widgets/auth/views/loginWithWebAuthnViewComponent.jsx
  src/widgets/auth/views/signupViewComponent.jsx
  src/widgets/auth/views/signupWithPasswordViewComponent.jsx
  src/widgets/auth/views/signupWithWebAuthnViewComponent.jsx
  src/widgets/webAuthn/webAuthnDevicesWidget.js
  tests/widgets/auth/__snapshots__/authWidget.test.js.snap
  tests/widgets/auth/authWidget.test.js
Labels: dependencies, enhancement

#73 Release v1.11.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#74 Revert SDK Core v1.17.2
  package-lock.json
  package.json
Labels: bug

#75 Release/v1.11.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
