Repository ReachFive/identity-web-ui-sdk, pull requests merged in 2020-01, with the labels that each got.

#10 Upgrade dependencies & fix security vulnerabilities
  package-lock.json
  package.json
Labels: dependency-upgrade

#11 Internationalise the widgets
  package-lock.json
  package.json
  rollup.config.js
  src/client.js
  src/components/widget/widget.jsx
  src/core/i18n.js
  src/i18n/en.js
  src/i18n/es.js
  src/i18n/fr.js
  src/i18n/it.js
  src/i18n/nl.js
  src/main.js
  tests/widgets/auth/__snapshots__/authWidget.test.js.snap
  tests/widgets/auth/authWidget.test.js
  tests/widgets/passwordReset/__snapshots__/passwordResetWidget.test.js.snap
  tests/widgets/passwordReset/passwordResetWidget.test.js
  tests/widgets/passwordless/__snapshots__/passwordlessWidget.test.js.snap
  tests/widgets/passwordless/passwordlessWidget.test.js
  tests/widgets/profileEditor/__snapshots__/profileEditorWidget.test.js.snap
  tests/widgets/socialAccounts/__snapshots__/socialAccountsWidget.test.js.snap
Labels: feature

#12 Release v1.0.0-alpha.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#14 Use our fork of zxcvbn with additional data
  package-lock.json
  package.json
  src/components/form/fields/passwordField.jsx
Labels: feature

#13 Generate UMD bundles
  package-lock.json
  package.json
  rollup.config.js
  src/components/form/fields/passwordField.jsx
  src/components/form/fields/phoneNumberField.jsx
Labels: feature

#15 Release v1.0.0-alpha.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#16 Update zxcvbn
  package-lock.json
  package.json
Labels: dependency-upgrade

#17 Release v1.0.0-alpha.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#18 Change the paths of the bundles
  .gitignore
  package.json
  rollup.config.js
Labels: enhancement

#19 Release v1.0.0-alpha.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
