Repository ReachFive/identity-web-ui-sdk, pull requests merged in 2020-02, with the labels that each got.

#20 Add the `returnTo` parameter for password reset et signup
  package-lock.json
  package.json
  src/client.js
  src/widgets/auth/views/forgotPasswordViewComponent.jsx
  src/widgets/auth/views/signupViewComponent.jsx
Labels: feature

#21 Release v1.0.0-alpha.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#22 Release v1.0.0-alpha.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#24 Enable the 'canShowPassword' property on the password reset widget
  src/widgets/passwordReset/passwordResetWidget.jsx
Labels: enhancement

#25 Release v1.0.0-alpha.9
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#23 Improve the UX/UI of the password policy rules
  src/components/form/fields/passwordField.jsx
  src/components/form/formControlsComponent.jsx
  src/components/form/passwordPolicyComponent.jsx
Labels: enhancement

#26 Release v1.0.0-alpha.10
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#27 Test the CircleCi 'deploy' job
  .circleci/config.yml
  package-lock.json
  package.json
Labels: for testing

#28 Fix the 'deploy' job
  .circleci/config.yml
Labels: bug

#29 Write a release guide & revert the test commit to fix the "deploy" job
  .circleci/config.yml
  RELEASE.md
  package-lock.json
  package.json
Labels: documentation
