Repository ReachFive/identity-web-ui-sdk, pull requests merged in 2020-04, with the labels that each got.

#33 Small technical improvements about dependencies and gitignore
  .gitignore
  package-lock.json
  package.json
Labels: enhancement, require review

#34 Upgrade the Core SDK version
  package-lock.json
  package.json
Labels: dependencies

#35 Release v1.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#36 Release v1.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#37 Move persistent in auth object
  src/widgets/auth/views/loginViewComponent.jsx
  tests/widgets/auth/__snapshots__/authWidget.test.js.snap
Labels: bug

#38 Release v1.2.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
