Repository ReachFive/identity-web-ui-sdk, pull requests merged in 2020-07, with the labels that each got.

#47 Implement a widget to manage fido2 devices
  index.d.ts
  src/client.js
  src/components/form/cardComponent.jsx
  src/main.js
  src/widgets/socialAccounts/socialAccountsWidget.jsx
  src/widgets/webAuthn/webAuthnDevicesWidget.js
  tests/widgets/socialAccounts/__snapshots__/socialAccountsWidget.test.js.snap
Labels: enhancement

#48 Release v1.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#49 Handle better error when device is already registered
  src/widgets/webAuthn/webAuthnDevicesWidget.js
Labels: enhancement

#50 Release v1.6.0
  CHANGELOG.md
  RELEASE.md
  package-lock.json
  package.json
Labels: release

#52 Display overloaded error message if there are
  src/components/form/formComponent.jsx
Labels: enhancement

#51 Ask the user to set the device's name
  package-lock.json
  package.json
  src/widgets/profileEditor/profileEditorWidget.jsx
  src/widgets/webAuthn/webAuthnDevicesWidget.js
Labels: dependencies, enhancement

#53 Release v1.7.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#54 Add custom fields types (email & phone)
  src/components/form/formFieldFactory.js
Labels: enhancement, require review

#55 Release v1.8.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
