Repository ReachFive/identity-web-ui-sdk, pull requests merged in 2020-05, with the labels that each got.

#39 Fix form validation
  src/components/form/fieldCreator.jsx
Labels: bug

#40 Default value false for remember me
  src/widgets/auth/views/loginViewComponent.jsx
  tests/widgets/auth/__snapshots__/authWidget.test.js.snap
Labels: enhancement

#41 Dependencies versions upgrade
  package-lock.json
  package.json
  rollup.config.js
  src/components/form/socialButtonsComponent.jsx
  src/components/miscComponent.jsx
  src/components/widget/widget.jsx
  src/components/widget/widgetContext.js
  src/widgets/auth/views/forgotPasswordViewComponent.jsx
  src/widgets/passwordEditor/passwordEditorWidget.jsx
  tests/widgets/auth/__snapshots__/authWidget.test.js.snap
  tests/widgets/passwordReset/__snapshots__/passwordResetWidget.test.js.snap
  tests/widgets/passwordless/__snapshots__/passwordlessWidget.test.js.snap
  tests/widgets/socialAccounts/__snapshots__/socialAccountsWidget.test.js.snap
Labels: dependencies

#42 Release v1.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
