Repository ReachFive/identity-web-ui-sdk, pull requests merged in 2021-01, with the labels that each got.

#80 Remove Instagram as social provider
  package-lock.json
  src/providers/instagram/instagram.js
  src/providers/instagram/instagram.svg
  src/providers/providers.js
Labels: require review

#81 Allow to make a consent mandatory
  src/components/form/fields/consentField.jsx
  tests/widgets/auth/__snapshots__/authWidget.test.js.snap
  tests/widgets/auth/authWidget.test.js
Labels: enhancement

#82 Release v1.11.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
