Repository ReachFive/identity-web-ui-sdk, pull requests merged in 2023-11, with the labels that each got.

#156 [CA-3185] [CA-3186] refactoring DateField with new UI and using Luxon
  src/components/form/fields/birthdayField.jsx
  src/components/form/fields/dateField.js
  src/components/form/fields/dateField.jsx
  src/components/form/formFieldFactory.js
  src/helpers/useDebounce.js
Labels: enhancement, require review

#159 [CA-3221] Supprimer le paramètre AT lors de l'appel à la méthode verifyMfaPasswordless du sdk core au niveau des widgets concernés
  package-lock.json
  package.json
  src/widgets/stepUp/mfaStepUpWidget.jsx
Labels: enhancement, dependencies

#160 Release v1.22.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#161 Release v1.23.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release, require review
