Repository ReachFive/identity-web-ui-sdk, pull requests merged in 2024-01, with the labels that each got.

#163 [CA-3237] Add new variable locale
  index.d.ts
  package-lock.json
  package.json
Labels: require review

#165 Release v1.24.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release, require review

#166 Bump testing-library/jest-dom from 6.1.2 to 6.2.0
  package-lock.json
  package.json
Labels: dependencies
