Repository ReachFive/identity-web-ui-sdk, pull requests merged in 2024-11, with the labels that each got.

#229 Release v1.29.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#221 [CA-3682] Optional password usage in showAuth widget
  src/components/form/formComponent.d.ts
  src/components/form/formComponent.jsx
  src/components/form/webAuthAndPasswordButtonsComponent.tsx
  src/widgets/auth/views/loginViewComponent.tsx
  src/widgets/auth/views/loginWithWebAuthnViewComponent.tsx
  src/widgets/auth/views/signupViewComponent.tsx
  tests/widgets/auth/__snapshots__/authWidget.test.js.snap
  tests/widgets/auth/authWidget.test.js
  types/identity-ui.d.ts
Labels: don't merge

#233 Release v1.30.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#236 [CA-4396] MFA factor selection does not appear when multiple factors are activated
  src/widgets/stepUp/mfaStepUpWidget.tsx
Labels: require review

#237 Release v1.30.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#238 Add purge CDN cache to release steps
  RELEASE.md
Labels: documentation
