Repository ReachFive/identity-web-ui-sdk, pull requests merged in 2025-03, with the labels that each got.

#271 Fix Kakao brand color
  src/providers/kakaotalk/kakaotalk.ts
Labels: require review

#272 [CA-4608] Update libphonenumber
  package-lock.json
  package.json
Labels: dependencies, require review

#269 [CA-4468] Add button to remove MFA credential
  jest.config.ts
  src/icons/comment-alt-dots.svg
  src/icons/envelope.svg
  src/widgets/mfa/mfaListWidget.tsx
  tests/widgets/mfa/__snapshots__/mfaListWidget.test.ts.snap
  tests/widgets/mfa/mfaListWidget.test.ts
  types/identity-ui.d.ts
Labels: require review

#273 [CA-4692] Phone number field validation should not triggered on initialization
  src/components/form/fields/phoneNumberField.tsx
  src/widgets/mfa/trustedDevicesWidget.tsx
Labels: require review

#274 Add test for trustedDevicesWidget
  src/widgets/mfa/trustedDevicesWidget.tsx
  tests/widgets/mfa/trustedDevicesWidget.test.ts
Labels: require review

#275 Realease v1.33.0
  CHANGELOG.md
  package-lock.json
  package.json
  types/identity-ui.d.ts
Labels: release

#279 Release v1.33.1
  CHANGELOG.md
  package-lock.json
  package.json
  types/identity-ui.d.ts
Labels: release
