Repository ReachFive/identity-web-ui-sdk, pull requests merged in 2025-01, with the labels that each got.

#245 [CA-4465] Add phone number input should only be displayed if no value is already defined
  src/widgets/mfa/MfaCredentialsWidget.tsx
  tests/widgets/mfa/MfaCredentialsWidget.test.js
  tests/widgets/mfa/__snapshots__/MfaCredentialsWidget.test.js.snap
  types/identity-ui.d.ts
Labels: require review

#247 Better theming in password field
  src/components/form/fields/passwordPolicyRules.tsx
  src/types/styled.d.ts
  types/identity-ui.d.ts
Labels: enhancement, require review

#249 Release v1.31.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/widget/widget.tsx
  tests/widgets/auth/__snapshots__/authWidget.test.js.snap
  tests/widgets/mfa/__snapshots__/MfaCredentialsWidget.test.js.snap
  tests/widgets/mfa/__snapshots__/mfaListWidget.test.js.snap
  tests/widgets/passwordReset/__snapshots__/passwordResetWidget.test.js.snap
  tests/widgets/passwordless/__snapshots__/passwordlessWidget.test.js.snap
  tests/widgets/profileEditor/__snapshots__/profileEditorWidget.test.js.snap
  tests/widgets/socialAccounts/__snapshots__/socialAccountsWidget.test.js.snap
  tests/widgets/socialLogin/__snapshots__/socialLogin.test.ts.snap
  types/identity-ui.d.ts
Labels: release

#250 Release v1.31.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/formComponent.jsx
  types/identity-ui.d.ts
Labels: release

#257 [CA-4542] Value the phone number to null when not specified
  rollup.config.js
  src/components/form/fields/phoneNumberField.tsx
Labels: bug, require review

#258 Release v1.31.3
  CHANGELOG.md
  package-lock.json
  package.json
  types/identity-ui.d.ts
Labels: release
