Repository ReachFive/identity-web-ui-sdk, pull requests merged in 2025-02, with the labels that each got.

#254 Replace remarkable with marked
  package-lock.json
  package.json
  src/components/miscComponent.tsx
Labels: dependencies, require review

#253 Replace luxon wih date-fns
  package-lock.json
  package.json
  src/components/form/fields/birthdayField.tsx
  src/components/form/fields/dateField.tsx
  src/types/index.d.ts
  tests/components/form/fields/dateField.test.tsx
  tests/components/form/fields/passwordField.test.tsx
Labels: dependencies, require review

#256 [CA-4472] Add trust device checkbox
  CHANGELOG.md
  src/widgets/auth/views/loginViewComponent.tsx
  src/widgets/auth/views/loginWithPasswordViewComponent.tsx
  src/widgets/stepUp/mfaStepUpWidget.tsx
  types/identity-ui.d.ts
Labels: require review

#260 Release v1.32.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/fields/dateField.tsx
  src/components/form/fields/phoneNumberField.tsx
  src/components/miscComponent.tsx
  tests/widgets/mfa/__snapshots__/MfaCredentialsWidget.test.js.snap
  tests/widgets/passwordless/__snapshots__/passwordlessWidget.test.js.snap
  types/identity-ui.d.ts
Labels: release

#263 Release v1.32.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/fields/birthdayField.tsx
  src/components/form/fields/dateField.tsx
  tests/components/form/fields/birthdateField.test.tsx
  types/identity-ui.d.ts
Labels: release

#264 Release v1.32.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/form/fields/birthdayField.tsx
  src/components/form/fields/dateField.tsx
  tests/components/form/fields/dateField.test.tsx
Labels: release

#262 Upgrade styled-components to v5.3.11
  package-lock.json
  package.json
  rollup.config.js
  tests/widgets/auth/__snapshots__/authWidget.test.js.snap
  tests/widgets/mfa/__snapshots__/MfaCredentialsWidget.test.js.snap
  tests/widgets/mfa/__snapshots__/mfaListWidget.test.js.snap
  tests/widgets/passwordReset/__snapshots__/passwordResetWidget.test.ts.snap
  tests/widgets/passwordless/__snapshots__/passwordlessWidget.test.js.snap
  tests/widgets/profileEditor/__snapshots__/profileEditorWidget.test.js.snap
  tests/widgets/socialLogin/__snapshots__/socialLogin.test.ts.snap
  types/identity-ui.d.ts
Labels: dependencies, require review

#267 [CA-4547] Fix phoneNumberField
  CHANGELOG.md
  src/components/form/fieldCreator.tsx
  src/components/form/fields/phoneNumberField.tsx
  tests/components/form/fields/phoneNumberField.test.tsx
  types/identity-ui.d.ts
Labels: require review

#265 Add tailwindcss framework to the project + support some theming for future components
  components.json
  package-lock.json
  package.json
  pnpm-lock.yaml
  postcss.config.cjs
  rollup.config.js
  src/components/ui/alert-dialog.tsx
  src/components/ui/button.tsx
  src/components/widget/widget.tsx
  src/index.css
  src/index.ts
  src/lib/utils.ts
  tailwind.config.cjs
  tsconfig.json
Labels: require review

#266 [CA-4504] Allow to list and remove trusted devices
  CHANGELOG.md
  src/client.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/button.tsx
  src/components/widget/widget.tsx
  src/helpers/utils.ts
  src/main.ts
  src/widgets/mfa/mfaListWidget.tsx
  src/widgets/mfa/trustedDevicesWidget.tsx
  tailwind.config.cjs
  types/identity-ui.d.ts
Labels: require review
